"""empty message

Revision ID: 32027183bc86
Revises: 66187d5dfc69
Create Date: 2020-01-07 16:39:36.530658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32027183bc86'
down_revision = '66187d5dfc69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('netid', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('netid')
    )
    op.create_table('postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('desc', sa.String(length=250), nullable=True),
    sa.Column('room', sa.String(length=50), nullable=False),
    sa.Column('building', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('diet', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('feeds', sa.Integer(), nullable=True),
    sa.Column('images', sa.ARRAY(sa.String(length=128)), nullable=True),
    sa.Column('owner_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.netid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['postings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.netid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendings')
    op.drop_table('postings')
    op.drop_table('users')
    # ### end Alembic commands ###
