"""empty message

Revision ID: 5b5ba3951eb0
Revises: c5692a6e1a1d
Create Date: 2019-11-10 23:08:43.105300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b5ba3951eb0'
down_revision = 'c5692a6e1a1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postings', sa.Column('test', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('postings', 'test')
    # ### end Alembic commands ###
