"""empty message

Revision ID: 60f64f8e1be3
Revises: 9d83d9de9f86
Create Date: 2019-12-24 13:28:23.258018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '60f64f8e1be3'
down_revision = '9d83d9de9f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['postings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.netid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('postings', 'num_going')
    op.drop_column('users', 'posts_going')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('posts_going', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('postings', sa.Column('num_going', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('attendings')
    # ### end Alembic commands ###
