"""empty message

Revision ID: aafa0fad83bf
Revises: 5b5ba3951eb0
Create Date: 2019-11-10 23:10:20.989353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aafa0fad83bf'
down_revision = '5b5ba3951eb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('postings', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postings', sa.Column('test', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
