"""empty message

Revision ID: c5692a6e1a1d
Revises: f0976c1a2ac9
Create Date: 2019-11-08 14:08:54.294568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5692a6e1a1d'
down_revision = 'f0976c1a2ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('desc', sa.String(length=250), nullable=True),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('building', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('diet', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('feeds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postings')
    # ### end Alembic commands ###
