"""empty message

Revision ID: c8d318085d95
Revises: aafa0fad83bf
Create Date: 2019-11-23 14:23:24.079872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d318085d95'
down_revision = 'aafa0fad83bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postings', sa.Column('images', sa.ARRAY(sa.String(length=128)), nullable=True))
    op.alter_column('postings', 'room',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('postings', 'room',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('postings', 'images')
    # ### end Alembic commands ###
