"""empty message

Revision ID: cc0c3e798563
Revises: 781da34af53f
Create Date: 2019-11-28 12:15:06.296674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc0c3e798563'
down_revision = '781da34af53f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('netid', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('netid')
    )
    op.add_column('postings', sa.Column('owner_id', sa.String(length=20), nullable=False))
    op.create_foreign_key(None, 'postings', 'users', ['owner_id'], ['netid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'postings', type_='foreignkey')
    op.drop_column('postings', 'owner_id')
    op.drop_table('users')
    # ### end Alembic commands ###
