"""empty message

Revision ID: f0976c1a2ac9
Revises: 30eca503b7d1
Create Date: 2019-11-06 20:59:36.853390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f0976c1a2ac9'
down_revision = '30eca503b7d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postings', sa.Column('building', sa.String(length=128), nullable=False))
    op.add_column('postings', sa.Column('diet', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('postings', sa.Column('feeds', sa.Integer(), nullable=True))
    op.add_column('postings', sa.Column('room', sa.String(length=50), nullable=True))
    op.drop_column('postings', 'location')
    op.drop_column('postings', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postings', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('postings', sa.Column('location', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('postings', 'room')
    op.drop_column('postings', 'feeds')
    op.drop_column('postings', 'diet')
    op.drop_column('postings', 'building')
    # ### end Alembic commands ###
